main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('aboutus', views.aboutus, name = 'aboutus'),
    path('contacts', views.contacts, name = 'contacts'),
    path('web_dev', views.web_dev, name = 'web_dev'),
    path('design', views.design, name = 'design'),
    path('adv', views.adv, name = 'adv'),
    path('call_request', views.call_request, name = 'call_request'),
    path('politica', views.politica, name = 'politica'),
    # api to api_url for sites / apps
    path('get_api_fabrika_edi', views.get_api_fabrika_edi, name = 'get_api_fabrika_edi'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render
from .models import * 
from django.http import JsonResponse, HttpResponse
import urllib
import os
from django.core.files.storage import default_storage
from mysite.settings import * 
import json
from django.template.loader import render_to_string
from datetime import datetime
from .telegrambot import *

from secure.api_tokens import * 

# Create your views here.

def index(request):
    template = 'main/index.html'
    context = {
        
    }
    return  render(request, template, context)

def aboutus(request):
    template = 'main/aboutus.html'
    context = {

    }
    return render(request, template, context)

def contacts(request):
    template = 'main/contacts.html'
    context = {

    }
    return render(request, template, context)
    

def web_dev(request):
    template = 'main/web_dev.html'
    context = {

    }
    return render(request, template, context)

def design(request):
    template = 'main/design.html'
    context = {
        
    }
    return render(request, template, context)

def adv(request):
    template = 'main/adv.html'
    context = {
        
    }
    return render(request, template, context)
    
    
def call_request(request):
    print('start sending call request')
    time = datetime.now()
    time = time.strftime("%Y-%m-%d-%H:%M")
    current_time = f'Время заявки: {time} \n'
    call_type = request.GET['call_type']
    if call_type == 'project':
        call_name = request.GET['call_name']
        call_phone = request.GET['call_phone']
        call_mail = request.GET['call_mail']
        call_about = request.GET['call_about']
        final_message =  '🔥 Заявка на обратный звонок 🔥 \n' + 'Сайт: mysite \n' + 'Тип: {} \n'.format(call_type) + f'Имя: {call_name} \n' + f'Телефон: {call_phone} \n' + f'Почта: {call_mail} \n' + f'О проекте: {call_about} \n' + current_time
        send_message(final_message)
    if call_type == 'phone_only':
        call_phone = request.GET['call_phone']
        final_message =  '🔥 Заявка на обратный звонок 🔥 \n' + 'Сайт: mysite \n' + 'Тип: {} \n'.format(call_type) + f'Телефон: {call_phone} \n' + current_time
        send_message(final_message)
    return JsonResponse({
        'send': True,
    }, status = 200)

def politica(request):
    template = 'main/politica.html'
    context = {

    }
    return render(request, template, context)

# api to api_url for sites / apps
def get_api_fabrika_edi(request):
    try:
        access_key = request.GET['access_token']
        if access_key == FABRIKA_EDI_ACCESS_TOKEN:
            # main_url = 'https://vkusno.fast-code.ru/'
            # api_url = 'https://vkusno.fast-code.ru/api/'
            main_url = 'https://food-fabrik.ru/'
            api_url = 'https://food-fabrik.ru/api/'
            return JsonResponse({
                'status': True,
                'main_url': main_url,
                'api_url': api_url,
                'access_token': FABRIKA_EDI_ACCESS_TOKEN_GRANT,
            })
        else:
            return JsonResponse({
                'status': False,
            })
    except:
        return JsonResponse({
        'status': False, 
        })


    

templates/main/aboutus.html
{% extends './base.html' %}
{% load static %}

{% block content %}

    <div class="aboutus_wrapper">

    <div class="page__header__container">
        <img class="page__header__container__img" 
        src="{% static 'images/about_bg.jpg' %}" alt="">
        <div class="page__header__container__bg">
        </div>
        <div class="page__header__container__title">
            <span>
                о нас
            </span>
        </div>
    </div>

    </div>

    {% include './blocks/we_can.html' %}

    {% include './blocks/serv_container.html' %}

    <div class="benefits_container">
        <div class="benefits_container_info">
            <div class="nice_title2 center benefits_container__title">
            <span>
                Стратегия
            </span>
            </div>
            <div class="benefits_container_info_list">
                <div class="benefits_container_info_item">
                    <div class="benefits_container_info_item__title">
                        <i class="fa fa-atom"></i>
                        <span>
                            Качественная и гибкая разработка
                        </span>
                    </div>
                    {% comment %} <div class="benefits_container_info_item__desc">
                        Выделенные проектные группы
                    </div> {% endcomment %}
                </div>
                <div class="benefits_container_info_item">
                    <div class="benefits_container_info_item__title">
                        <i class="fa fa-atom"></i>
                        <span>
                        Современные и надежные технологии
                        </span>
                    </div>
                </div>
                <div class="benefits_container_info_item">
                    <div class="benefits_container_info_item__title">
                        <i class="fa fa-atom"></i>
                        <span>
                            Персональный подход к каждому клиенту
                        </span>
                    </div>
                </div>
                <div class="benefits_container_info_item">
                    <div class="benefits_container_info_item__title">
                        <i class="fa fa-atom"></i>
                        <span>
                        Выделенные проектные группы
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% include './blocks/request_call.html' %}

{% endblock content %}

templates/main/adv.html
{% extends './base.html' %}
{% load static %}

{% block content %}

    
<div class="case-main dark case-main-top">
    <div class="case-main-text design-header-title">
        <h3 class="case-main__title case-f aos-init aos-animate" data-aos="fade-down">
            {% block intro__container__title %}
                Реклама вашего бизнеса
            {% endblock intro__container__title %}
        </h3>
        <div class="case-main__subtitle">
            Google, Yandex <br>
            Facebook, VK<br>
        </div>
        <p class="case-main__desc aos-init aos-animate" data-aos="fade-down" data-aos-delay="150">
        </p>
    </div>
    <div class="case-main-img-wrapper">
        <noscript><img data-aos-anchor=".case-main__title" data-aos-duration="700" data-aos="fade-left" data-aos-delay="250" 
            src="{% static 'images/adv_main2.png' %}" alt=""></noscript>
        <img class="aos-init lazyloaded aos-animate" data-aos-anchor=".case-main__title" data-aos-duration="700" data-aos="fade-left" data-aos-delay="250" src="{% static 'images/adv_main2.png' %}" data-src="{% static 'images/adv_main2.png' %}" alt="">
    </div>
</div>

{% comment %} sale container  {% endcomment %}
    <div class="sale__container">
        <img class="sale__container__img"
        src="{% static 'images/sale_container_bg.png' %}" alt="">
        <div class="sale__container__bg">
        </div>
        <div class="sale__container__title">
            Дизайн в подарок при заказе сайта
        </div>
        <div class="nice_button sale__container__button">
            <span>
                Узнать больше
            </span>
        </div>
    </div>
{% comment %}  end sale container {% endcomment %}


    {% comment %} benefits container {% endcomment %}
    <div class="benefits__wrapper">
        <div class="nice_title2 center">
            <span>
                Зачем нужна настройка рекламы
            </span>
        </div>
        <div class="benefits">
            <div class="benefits__image">
                <img src="{% static 'images/adv_main3.png' %}" alt="">
            </div>
            <div class="benefits__items">
                <div class="benefits__items__item">
                    <i class="fa fa-chevron-right"></i>
                    <span>
                        Вас увидят в поисковиках, мобильных приложениях, YouTube, в ленте и сообществах Вконтакте
                    </span>
                </div>
                <div class="benefits__items__item">
                    <i class="fa fa-chevron-right"></i>
                    <span>
                        Только целевая аудитория. Реклама будет показываться пользователям, которые ищут ваш товар или заинтересованы в нем.
                    </span>
                </div>
                <div class="benefits__items__item">
                    <i class="fa fa-chevron-right"></i>
                    <span>
                        Постоянный рост эффективности. Каждый месяц мы анализируем результаты и перераспределяем бюджет в пользу работающих решений.
                    </span>
                </div>
                <div class="benefits__items__item">
                    <i class="fa fa-chevron-right"></i>
                    <span>
                        Платите за результат. Вы платите только когда пользователь переходит на сайт или звонит вам.
                    </span>
                </div>
            </div>
        </div>
    </div>
    {% comment %} end benefits container {% endcomment %}


    {% include './blocks/request_call.html' %}

    {% include './blocks/serv_container.html' %}

    {% include './blocks/contacts_container.html' %}
    

{% endblock content %}

templates/main/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FastCode - создание сайтов и дизайн</title>

    <!-- Yandex.Metrika counter -->
<script type="text/javascript" >
   (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
   m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
   (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

   ym(71868796, "init", {
        clickmap:true,
        trackLinks:true,
        accurateTrackBounce:true,
        webvisor:true
   });
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/71868796" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->


</head>
<body>

{% include './includes_css.html' %}
{% include './includes_js.html' %}



{% block header %}
    <div class="main__header__block__wrapper">
        <div class="main__header__block">
            {% include './blocks/header.html' %}
        </div>
    </div>

{% endblock header %}


{% block content %}
{% endblock content %}

    {% include './blocks/footer.html' %}

    {% include './blocks/popup_cotact.html' %}

    {% include './blocks/popup_complete.html' %}


</body>

<script>
  
function sendCall(call_type) {
    console.log('button is clicked')
    console.log(call_type)
    if (call_type == 'project') {
        var call_name = $("input[name='call_name']").val()
        var call_phone = $("input[name='call_phone']").val()
        var call_mail = $("input[name='call_mail']").val()
        var call_about = $("input[name='call_about']").val()
        $.ajax({
            url: "{% url 'main:call_request' %}",
            data: {
                'call_type': call_type,
                'call_name': call_name,
                'call_phone': call_phone,
                'call_mail': call_mail,
                'call_about': call_about,
            }, success: function(data) {
                openThankPopup()
            }
        });
    }
    if (call_type == 'phone_only') {
        var call_phone = $("input[name='call_phone2']").val()
        $.ajax({
            url: "{% url 'main:call_request' %}",
            data: {
                'call_type': call_type,
                'call_phone': call_phone,
            }, success: function(data) {
                openThankPopup()
            }
        });
    }
    if (call_type == 'popup_phone') {
        var call_phone = $("input[name='call_phone3']").val()
        $.ajax({
            url: "{% url 'main:call_request' %}",
            data: {
                'call_type': 'phone_only',
                'call_phone': call_phone,
            }, success: function(data) {
                closeContactPopup()
                openThankPopup()
            }
        });
    }
}

function checkForm(call_type) {
    var passed = true
    if (call_type == 'project') {
        var call_name = $("input[name = 'call_name']")
        var call_phone = $("input[name = 'call_phone']")
        if ($(call_name).val().length < 1) {
            $(call_name).addClass('alert')
            passed = false
        } else {
            $(call_name).removeClass('alert')
        }
        if ($(call_phone).val().length < 1) {
            $(call_phone).addClass('alert')
            passed = false
        } else {
            $(call_phone).removeClass('alert')
        }
        return passed
    }
    if (call_type == 'phone_only') {
        var call_phone = $("input[name = 'call_phone2']")
        if ($(call_phone).val().length < 1) {
            $(call_phone).addClass('alert')
            passed = false
        } else {
            $(call_phone).removeClass('alert')
        }
        return passed
    }
    if (call_type == 'popup_phone') {
        var call_phone = $("input[name = 'call_phone3']")
        if ($(call_phone).val().length < 1) {
            $(call_phone).addClass('alert')
            passed = false
        } else {
            $(call_phone).removeClass('alert')
        }
        return passed
    }
}
function openThankPopup() { 
    $("#thank_popup").addClass("show")
    $(".contacts_popup_bg").addClass("show")
}
function closeThankPopup() { 
    $("#thank_popup").removeClass("show")
    $(".contacts_popup_bg").removeClass("show")
}

$('#send_call_phone').click(function() {
    var call_type = 'project'
    var passed = checkForm(call_type)
    if (passed == true) {
        sendCall(call_type)
    }
})

$('#send_call_phone2').click(function() {
    var call_type = 'phone_only'
    var passed = checkForm(call_type)
    if (passed == true) {
        sendCall(call_type)
    }
})
$('#send_call_phone3').click(function() {
    var call_type = 'popup_phone'
    var passed = checkForm(call_type)
    if (passed == true) {
        sendCall(call_type)
    }
})

$('#thank_popup_close').click(function() {
    closeThankPopup()
})

$(".main__header__phone__callme").click(function() {
    openContactPopup()
})
$(".popup_contact_close").click(function() {
    closeContactPopup()
})
$(".popup_contact_bg").click(function() {
    closeContactPopup()
})

$(".sale__container__button").click(function() {
    openContactPopup()
})

function openContactPopup() {
    $(".popup_contact").addClass("show")
    $(".popup_contact_bg").addClass("show")
}
function closeContactPopup() {
    $(".popup_contact").removeClass("show")
    $(".popup_contact_bg").removeClass("show")
}



</script>

</html>

templates/main/blocks/contacts_container.html
<div class="contacts_container_wrapper__main">
    <div class="contacts_container_wrapper">
        <div class="contacts_content1">
            <div class="contacts__title">
                Наши контакты
            </div>
            <!-- <div class="contact__item">
                <div class="contact__item__icon">
                    <i class="fa fa-route"></i>
                </div>
                <div class="contact__item__text">
                    Симферополь, ул. Киевская, д. 126
                </div>
            </div> -->
            <div class="contact__item">
                <div class="contact__item__icon">
                    <i class="fa fa-phone-alt"></i>
                </div>
                <div class="contact__item__text">
                    <a href="tel:+79782215509">
                    +7 (978)-221-55-09
                    </a>
                </div>
            </div>
        </div>
        <div class="contacts_content2">
            <div class="contacts__title2">
                Сделаем Ваш проект еще лучше!
            </div>

            <input name="call_phone2"
            class="contact__form__input"
                type="text" placeholder="Телефон*">
            <div class="contact2_button contact__form">
                <span class="nice_button">
                    <span id="send_call_phone2">
                    Узнать как
                    </span>
                </span>
            </div>
        </div>
    </div>
    </div>

templates/main/blocks/footer.html
{% load static %}
<div class="footer_wrapper">
    <div class="footer_content">
        <div class="footer_first">
            <div class="footer_logo footer_item">
                <img src="{% static 'images/main_logo.svg' %}" alt="">
            </div>
            <div class="footer_company footer_item">
                FastCode - 2021
            </div>
            <div class="footer_policy footer_item">
                <a target="blank" 
                href="{% url 'main:politica' %}">
                Политика конфиденциальности
                </a>
            </div>
        </div>
       <div class="footer_second footer_item">
           <span>
           Контакты
           </span>
           <div class="footer_second__number">
                <a href="tel:+79782215509">
                +7(978)-221-55-09
                </a>
           </div>
       </div>
    </div>
</div>

templates/main/blocks/h_first.html
<div class="main__header__first">
    <div class="main__header__first__container">
        <div class="header__first__container__item">
            О нас
        </div>
        <div class="header__first__container__item">
            Доставка
        </div>
        <div class="header__first__container__item">
            Оплата
        </div>
    </div>
</div>

templates/main/blocks/header.html
<!-- {% include './h_first.html' %} -->
{% load static %}


<div class="main__header__second__mobile__logo">
    <a class="header__second__logo mobile__logo"
    href="{% url 'main:index' %}">
        <img src="{% static 'images/main_logo.svg' %}" alt="">
    </a>

    <!-- <div class="header__second__search">
        <form
        class="header__second__search__form">
            {% csrf_token %}
            <input type="text" class="input_search"
            name="search_input"
            placeholder="Искать">
            <button class="input_submit">
                <i class="gg-search"></i>
            </button>
        </form>
    </div> -->

</div>

<div class="main__header__second">
    <a class="header__second__logo logo__big"
    href="{% url 'main:index' %}">
        <img src="{% static 'images/main_logo.svg' %}" alt="">
    </a>

    <div class="header__second__catalog">
        <div class="header__second__catalog__items">
            <a href="{% url 'main:index' %}">
                Главная
            </a>
        </div>
        <div class="header__second__catalog__items">
            <a href="{% url 'main:index' %}#services_anchor">
                Услуги
            </a>
        </div>
        <div class="header__second__catalog__items">
            <a
            href="{% url 'main:aboutus' %}">
                о компании
            </a>
        </div>
        <div class="header__second__catalog__items">
            <a
            href="{% url 'main:contacts' %}">
                Контакты
            </a>
        </div>
        
    </div>

    <div class="main__header__phone">
        <i class="fa fa-phone-alt
        contact_with_us_icon"></i>
        <div class="main__header__phone__callme">
            <div class="main__header__phone__callme callme_link contact_title">
                Связаться с нами
            </div> 
            <span class="contact_with_us_phone">
                +7(978)-221-55-09
            </span>
        </div>
    </div>

    <div class="header__second__catalog__mobile__wrapper">
    <span class="header__second__catalog__mobile">
        <div class="header__second__catalog__mobile__items">
            <i class="gg-menu-left-alt"></i>
            <span href="">
                Меню
            </span>
        </div>
    </span>
    </div>    

    <div class="main__header__phone__mobile">
        <!-- <div class="main__header__phone__main">
            <i class="fa fa-phone-alt"></i>
            <div class="main__header__phone__main__text">
                <a href="tel:+79781161415">
                    +7 (978) 116-14-15
                </a>
            </div>
        </div> -->
        <!-- <div class="main__header__phone__callme">
            <span class="main__header__phone__callme callme_link">
                Заказать звонок
            </span>
        </div>
    </div> -->

    <!-- <div class="main__header__phone"> -->
        <i class="fa fa-phone-alt
        contact_with_us_icon"></i>
        <div class="main__header__phone__callme">
            <div class="main__header__phone__callme callme_link contact_title">
                Связаться с нами
            </div> 
            <span class="contact_with_us_phone">
                +7(978)-221-55-09
            </span>
        </div>
    <!-- </div> -->


    <div class="header__second__icons">



        <!-- <a class="header__second__icons__item account__big">
            <svg height="24" viewBox="0 0 20 20" width="24"><path d="M16.984 14.506V17H3.016v-2.494C4.47 11.794 6.797 10.438 10 10.438s5.531 1.356 6.984 4.068zM10 11.938c-2.528 0-4.295.958-5.484 2.961v.6h10.968v-.6c-1.19-2.003-2.956-2.961-5.484-2.961zm3.686-6.384a3.686 3.686 0 11-7.372 0 3.686 3.686 0 017.372 0zm-1.5 0a2.186 2.186 0 10-4.372 0 2.186 2.186 0 004.372 0z"></path></svg>
        </a> -->

    </div>
</div>


<div class="header__popup__mobile">
    <div class="header__popup__mobile__menu">
        <a href="{% url 'main:index' %}"
            class="mobile__nav">
                Главная
            </a>
            <a href="{% url 'main:index' %}#services_anchor"
            class="mobile__nav">
                Услуги
            </a>
            <a
            href="{% url 'main:aboutus' %}"
            class="mobile__nav">
                о компании
            </a>
            <a
            href="{% url 'main:contacts' %}"
            class="mobile__nav">
                контакты
            </a>
    </div>
</div>
<div class="header__popub__mobile__close">
    <i class="fa fa-close"></i>
</div>
<div class="header__popup__mobile__wrapper">

</div>



<script>
    // $(".header__second__catalog").click(function() {
    //     $(".catalog_open").toggleClass("hide")
    //     $(".catalog_close").toggleClass("show")
    //     $(".header__second__catalog").toggleClass("opened")
    //     $(".header__second__catalog__items").toggleClass("opened")
    // })
    $(".header__second__catalog__mobile").click(function() {
        openMobileMenu()
    })
    $(".header__popub__mobile__close").click(function() {
        closeMobileMenu()
    })
    $(".mobile__nav").click(function() {
        closeMobileMenu()
    })


    function openMobileMenu() {
            $(".header__popup__mobile").addClass("show")
            $(".header__popub__mobile__close").addClass("show")
            $("body").addClass("hidden")
        }
    function closeMobileMenu() {
            $(".header__popup__mobile").removeClass("show")
            $(".header__popub__mobile__close").removeClass("show")
            $("body").removeClass("hidden")
        }
</script>

templates/main/blocks/popup_complete.html
<div class="contacts_popup"
    id="thank_popup">
    <div class="contacts_popup_content">
        <div class="nice_title2 center light">
            <span>
                Ваша заявка принята
            </span>
        </div>
        <div class="contacts_popup_subtitle">
            <span>
                Наш менеджер скоро свяжется с Вами.
            </span>
        </div>
        <div class="nice_button red wide contacts_popup_button">
            <span id="thank_popup_close">
                Закрыть
            </span>
        </div>
    </div>
</div>
<!-- bg for contacts popup -->
<div class="contacts_popup_bg"></div>

templates/main/blocks/popup_cotact.html
<div class="popup_contact">
    <div class="popup_contact_content">
        <div class="nice_title2 light center">
            <span>
                Оставить заявку
            </span>
        </div>
        <div class="popup_contact_content_description">
            <span>
                Наш менеджер скоро свяжется с Вами 
            </span>
        </div>
        <div class="popup_contact_content_form">
            <input 
            class="call_form_input nobg popup_contact_content_form__input"
            placeholder="Телефон*"
            type="text" 
            name="call_phone3">
            <div class="nice_button thin center popup_contact_content_form_btn"
            id="send_call_phone3">
                <span>
                    Отправить
                </span>
            </div>
        </div>
    </div>
    <div class="popup_contact_close">
        <i class="fa fa-close popup__contact__close"></i>
    </div>
</div>
<div class="popup_contact_bg">
</div>

templates/main/blocks/request_call.html
<div class="request_call_container">
    <div class="nice_title2">
        <span>
            Обсудим ваш проект?
        </span>
    </div>
    <div class="request_call_form">
        <div class="request_call_form_first">
            <input class="call_form_input" 
            name="call_name" autocomplete="off" 
            placeholder="Имя*"
            type="">
            <input class="call_form_input" 
            name="call_phone" autocomplete="off" 
            placeholder="Телефон*"
            type="">
            <input class="call_form_input" 
            name="call_mail" autocomplete="off" 
            placeholder="Почта"
            type="">
        </div>
        <div class="request_call_form_first_second">
            <input class="call_form_input call_form_input_about" 
            name="call_about" autocomplete="off" 
            placeholder="Расскажите о вашем проекте"
            type="">
        </div>
        <div class="request_call_send nice_button">
            <span id="send_call_phone">
                отправить
            </span>
        </div>
    </div>
</div>

templates/main/blocks/serv_container.html
{% load static %}
<div class="serv_container_wrapper">
    <div class="serv_container">
        <div class="serv_container_item">
            <img class="serv_container_item__image"
            src="{% static 'images/webdev.jpg' %}" alt="">
            <div class="serv_container_item__bg">
            </div>
            <div class="serv_container_item__info">
                <div class="serv_container_item__info__title">
                    <span class="">
                    Веб-разработка
                    </span>
                </div>
                <div class="serv_container_item__info__desc">
                    Разработка сайтов любой сложности: от простого лендинга до крупного сайта-портала. <br>
                    Комплексное продвижение Вашего бизнеса за счет SEO-оптимизации и правильной контекстной рекламы.

                    <div class="serv_container_item__info__button nice_button">
                        <a href="{% url 'main:web_dev' %}">
                        подробнее
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="serv_container_item">
        <img class="serv_container_item__image"
            src="{% static 'images/designdev.jpg' %}" alt="">
        <div class="serv_container_item__bg">
        </div>
            <div class="serv_container_item__info">
                <div class="serv_container_item__info__title">
                    <span>
                    Дизайн
                    </span>
                </div>
                <div class="serv_container_item__info__desc">
                    Разработка эксклюзивного логотипа, создание фирменного стиля, редизайн сайта.
                    <div class="serv_container_item__info__button nice_button">
                        <a href="{% url 'main:design' %}">
                        подробнее
                        </a>
                    </div>

                </div>

            </div>
        </div>
        <div class="serv_container_item">
        <img class="serv_container_item__image"
            src="{% static 'images/marketingdev.svg' %}" alt="">
        <div class="serv_container_item__bg">
        </div>
            <div class="serv_container_item__info">
                <div class="serv_container_item__info__title">
                    <span>
                    Реклама
                    </span>
                </div>
                <div class="serv_container_item__info__desc">
                    Настройка и ведение рекламных компаний Yandex, Google, Vk, Instagram, Facebook.
                    <div class="serv_container_item__info__button nice_button">
                        <a href="{% url 'main:adv' %}">
                        подробнее
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(".serv_container_item").hover(function() {
        var colors = [
            'red', 'blue', 'green', 'yellow', 'orange', 'violet'
        ]
        var random_color = colors[Math.floor(Math.random()*colors.length)];
        $(this).addClass("hover")
        var item = $(this).find(".serv_container_item__info__title span").addClass('underline ' + random_color)
        console.log(item)
    }, function() {
        $(this).removeClass("hover")
        var item = $(this).find(".serv_container_item__info__title span").attr('class', '')
    })
</script>

templates/main/blocks/we_can.html
<div class="we_can_wrapper">
    <div class="nice_title2 center">
        <span>
            Что мы умеем
        </span>
    </div>
    <div class="we_can_container">
        <div class="we_can_item">
            <i 
            class="fa fa-chevron-right we_can_item__icon">
            </i>
            <span class="we_can_item__text">
                Разработка лендингов, сайтов, интернет-магазинов
            </span>
        </div>
        <div class="we_can_item">
            <i 
            class="fa fa-chevron-right we_can_item__icon">
            </i>
            <span class="we_can_item__text">
                Создание логотипа, фирменного стиля, редизайн сайта
            </span>
        </div>
        <div class="we_can_item">
            <i 
            class="fa fa-chevron-right we_can_item__icon">
            </i>
            <span class="we_can_item__text">
                Реклама вашего бизнеса в Google, Yandex, Facebook, Vk.
            </span>
        </div>
    </div>
</div>